### ISSUE TITLE
Interface freezes while building the initial mod list

### ISSUE THREAD

**Issue by Banane9** [XDelta/NeosModManager#12]
The window was unresponsive after relaunching the mod manager after setting the neos path and such.

I assume this was caused by scanning the mod folder or downloading the manifest file.

**Comment by XDelta** [comment]
Freezing entirely? May need a log from that. It should only take a few seconds from opening to a list being shown.

**Comment by Banane9** [comment]
It froze for a good 10s or so... happened when I just started it again too.

It would appear that scanning and hashing the files is what's taking some time (this is on an M.2 SSD)

[log20230604.log](https://github.com/XDelta/NeosModManager/files/11645799/log20230604.log)

**Comment by XDelta** [comment]
This looks to me like some protection software would be interfering and slowing it down significantly while it is creating hashes of your local mods. From the timestamps it looks like about~half a second on average between those listed mods with some having over a second. Should be more along only a couple milliseconds between those even accounting for many mods between.

**Comment by Banane9** [comment]
I'm not sure - when re-running it by pressing check for updates or relaunching it, it only takes a second or so.

**Comment by XDelta** [comment]
Going to close assuming it was the cause of some protection software wanting to jump in and scan the dlls as they were being read to create a hash.

**Comment by Banane9** [comment]
I mean, the real fix would be, to not do the loading on the UI thread (when refreshing it seems to update still?) 👀
