### ISSUE TITLE
iTrackerFix mod downloads file with wrong hash compared to manifest

### ISSUE THREAD

**Issue by Nytra** [XDelta/NeosModManager#15]
This is strange because if you download the mod file directly from GitHub it has the correct hash, but downloading it through the mod manager gives a file with the wrong hash. So I think the mod manager is changing this file somehow to give it a different hash.

Also the mod does not appear checked in the mod manager after downloading it.

**Comment by XDelta** [comment]
Looking into it at the moment.

**Comment by XDelta** [comment]
Looks like this is actually an issue on the manifest actually. The provided download link isn't correct. Making a PR there to fix it.

**Comment by XDelta** [comment]
https://github.com/neos-modding-group/neos-mod-manifest/pull/302

**Comment by XDelta** [comment]
Fixed download link merged in on manifest
