### ISSUE TITLE
mod with a non standard name behave weirdly

### ISSUE THREAD

**Issue by art0007i** [XDelta/NeosModManager#2]
I have a mod in my mods folder called `ReArmature (1).dll`, the mod manager detects the mod just fine, but trying to disable the mod will not do anything (not even a message in the log saying it tried to disable it or an error that would actually say what happened)

trying to update that mod, doesn't delete the original dll either so you end up with 2 dlls `ReArmature (1).dll` (the old version) and `ReArmature.dll` the new version created by the manager

**Comment by XDelta** [comment]
Should now be fixed in 0.3.1
